# Generated by Django 5.2.13 on 2026-04-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='User mobile number', max_length=20, null=True),
        ),
    ]
